# -*- coding: utf-8 -*-
import csv

columns = [
    "id",
    "plataforma",
    "empresa_operadora",
    "categoria",
    "naturaleza_publico_privado",
    "pais_origen_matriz",
    "marco_legal_declarado",
    "datos_personales_recolectados",
    "comparte_datos_terceros",
    "transferencia_internacional_datos",
    "uso_publicitario_perfilamiento",
    "exposicion_publica_contenido_por_defecto",
    "mecanismo_consentimiento",
    "resolucion_disputas",
    "derecho_eliminacion_portabilidad_datos",
    "url_politica_privacidad",
    "fecha_version_politica",
    "fecha_consulta",
    "notas",
]

rows = [
{
 "plataforma": "Facebook e Instagram",
 "empresa_operadora": "Meta Platforms, Inc. (Meta Platforms Ireland Ltd. para usuarios fuera de EE.UU./Canadá)",
 "categoria": "red_social",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "Estados Unidos",
 "marco_legal_declarado": "GDPR (UE/EEE); CCPA/leyes estatales de EE.UU.; no menciona Ley 19.628 ni Ley 21.719 de Chile",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; biometricos; contenido_generado; comportamiento_navegacion; datos_dispositivo",
 "comparte_datos_terceros": "parcial",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "si",
 "exposicion_publica_contenido_por_defecto": "configurable",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "jurisdiccion_extranjera",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://www.facebook.com/privacy/policy/",
 "fecha_version_politica": "Actualización relevante 16-dic-2025 (uso de chats de Meta AI para publicidad); fecha exacta no verificable (bloqueo robots.txt)",
 "fecha_consulta": "2026-09-02",
 "notas": "Desde dic-2025 Meta usa contenido de chats con Meta AI para personalizar anuncios, sin opción clara de exclusión total. Resolución de disputas ante tribunales de EE.UU. (Norte de California/San Mateo), no arbitraje forzado.",
},
{
 "plataforma": "WhatsApp",
 "empresa_operadora": "WhatsApp LLC (Meta Platforms, Inc.); WhatsApp Ireland Ltd. fuera de EE.UU./Canadá",
 "categoria": "mensajeria",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "Estados Unidos",
 "marco_legal_declarado": "GDPR (UE/EEE); CCPA (aviso separado California); no menciona leyes chilenas",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; datos_dispositivo; contenido_generado; comportamiento_navegacion",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "parcial",
 "exposicion_publica_contenido_por_defecto": "privado_por_defecto",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "no_especifica",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://www.whatsapp.com/legal/privacy-policy",
 "fecha_version_politica": "4 de enero de 2021 (última actualización mayor confirmada; documento global)",
 "fecha_consulta": "2026-09-02",
 "notas": "Mensajes cifrados extremo a extremo, pero se comparte metadata con 'Meta Companies'. La FNE de Chile investigó su actualización de 2021 y archivó el caso en 2025. Sin publicidad dentro de chats; sí en Estados/Canales.",
},
{
 "plataforma": "TikTok",
 "empresa_operadora": "TikTok Pte. Ltd. / TikTok Technology Ltd. (matriz ByteDance Ltd.); entidad EE.UU. reestructurada como 'TikTok USDS Joint Venture LLC' desde ene-2026",
 "categoria": "red_social",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "China (ByteDance Ltd., con operación dual en Singapur)",
 "marco_legal_declarado": "GDPR (versión EEE); ley de California rige los ToS; sin mención de leyes chilenas",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; biometricos; comportamiento_navegacion; contenido_generado; datos_dispositivo",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "si",
 "exposicion_publica_contenido_por_defecto": "configurable",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "arbitraje_privado",
 "derecho_eliminacion_portabilidad_datos": "parcial",
 "url_politica_privacidad": "https://www.tiktok.com/legal/page/row/privacy-policy/en",
 "fecha_version_politica": "No verificable con certeza (bloqueo robots.txt); versión EEE conocida de 2-nov-2022; versión EE.UU. reformulada vigente desde 22-ene-2026 (no aplica a Chile)",
 "fecha_consulta": "2026-09-02",
 "notas": "En 2026 TikTok separó su entidad de EE.UU. (venta forzada, joint venture con Oracle); Chile queda bajo la entidad internacional 'Rest of World'. Arbitraje vinculante en California (condado de Santa Clara) para disputas no arbitrables ante cortes menores.",
},
{
 "plataforma": "X (antes Twitter)",
 "empresa_operadora": "X Corp. (matriz X Holdings Corp.)",
 "categoria": "red_social",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "Estados Unidos",
 "marco_legal_declarado": "Declara cumplimiento con DSA (UE), Online Safety Act (UK) y regulaciones australianas; ley de Texas rige el ToS; sin mención de leyes chilenas",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; biometricos; comportamiento_navegacion; contenido_generado; datos_dispositivo",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "si",
 "exposicion_publica_contenido_por_defecto": "publico_por_defecto",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "jurisdiccion_extranjera",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://x.com/es/privacy",
 "fecha_version_politica": "15 de enero de 2026",
 "fecha_consulta": "2026-09-02",
 "notas": "Verificación de identidad usa datos biométricos vía proveedor externo AU10TIX, retenidos ~30 días. Publicaciones públicas por defecto salvo cuenta 'protegida'. Renuncia a acciones colectivas; jurisdicción en Texas.",
},
{
 "plataforma": "LinkedIn",
 "empresa_operadora": "LinkedIn Corporation (matriz Microsoft Corporation); LinkedIn Ireland Unlimited Company fuera de EE.UU./Canadá",
 "categoria": "red_social",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "Estados Unidos",
 "marco_legal_declarado": "GDPR; EU-US Data Privacy Framework; Swiss-US DPF; leyes estatales de EE.UU. (vía Declaración de Privacidad de Microsoft); sin mención de leyes chilenas",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; comportamiento_navegacion; contenido_generado; datos_dispositivo; datos_laborales",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "parcial",
 "exposicion_publica_contenido_por_defecto": "configurable",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "no_especifica",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://www.linkedin.com/legal/privacy-policy",
 "fecha_version_politica": "Actualización relevante 3-nov-2025 (uso de datos de perfil para entrenar IA de Microsoft); fecha exacta no verificable (bloqueo robots.txt)",
 "fecha_consulta": "2026-09-02",
 "notas": "Desde nov-2025 LinkedIn usa datos de perfil para entrenar modelos de IA de Microsoft, con opción de exclusión disponible en configuración. Mecanismo exacto de resolución de disputas del User Agreement no verificable por bloqueo de acceso directo.",
},
{
 "plataforma": "Mercado Libre / Mercado Pago",
 "empresa_operadora": "Mercado Libre Chile Limitada (RUT 77.398.220-1) y Mercado Pago S.A. (RUT 76.516.950-K); matriz MercadoLibre Inc.",
 "categoria": "ecommerce",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "Argentina (matriz operativa; MercadoLibre Inc. incorporada en Delaware, EE.UU.)",
 "marco_legal_declarado": "Normativa chilena de protección de la vida privada (Ley 19.628 implícita, sin número explícito) y regulación de cada país donde opera; no menciona Ley 21.719",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; biometricos; financieros; comportamiento_navegacion; datos_dispositivo; contenido_generado",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "si",
 "exposicion_publica_contenido_por_defecto": "configurable",
 "mecanismo_consentimiento": "opt_in",
 "resolucion_disputas": "tribunales_chile",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://www.mercadolibre.cl/privacidad/declaracion-privacidad/31199",
 "fecha_version_politica": "31 de agosto de 2021 (fecha mostrada en el anexo consultado)",
 "fecha_consulta": "2026-09-02",
 "notas": "Declara uso de IA/machine learning/big data para perfilamiento y decisiones automatizadas (con derecho a revisión). Reputación/calificaciones del vendedor son públicas por defecto aunque el resto del perfil es configurable. La fecha de 'última actualización' visible (2021) parece desactualizada para septiembre 2026; no se confirmó una fecha más reciente (bloqueo robots.txt).",
},
{
 "plataforma": "Falabella.com (Falabella Retail)",
 "empresa_operadora": "Falabella.com SpA (RUT 76.212.492-0) / Falabella Retail S.A.; comparte 'Habeas Data' corporativo con Banco Falabella, CMR, Sodimac, Tottus e Ikea Chile",
 "categoria": "ecommerce",
 "naturaleza_publico_privado": "privada_nacional",
 "pais_origen_matriz": "Chile (S.A.C.I. Falabella)",
 "marco_legal_declarado": "'Normas que regulan la protección de la vida privada' (Ley 19.628 implícita, sin número explícito); no menciona Ley 21.719",
 "datos_personales_recolectados": "identificacion; contacto; financieros; biometricos; ubicacion; comportamiento_navegacion; datos_dispositivo",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "no_especifica",
 "uso_publicitario_perfilamiento": "si",
 "exposicion_publica_contenido_por_defecto": "no_aplica",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "no_especifica",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://www.falabella.com/falabella-cl/page/politica-privacidad-falabella-retail",
 "fecha_version_politica": "28 de febrero de 2023 (según metadatos); documento protocolizado notarialmente el 14-12-2021",
 "fecha_consulta": "2026-09-02",
 "notas": "Comparte datos entre empresas del grupo Falabella (incluida su tarjeta CMR / Banco Falabella) bajo un esquema de 'Habeas Data' corporativo compartido. No se verificó con fuente directa el mecanismo de resolución de disputas ni el detalle completo de transferencias internacionales (solo se mencionan operaciones regionales en Chile, Perú y Colombia).",
},
{
 "plataforma": "Uber / Uber Eats",
 "empresa_operadora": "Nivel local (T&C Chile): Uber Rides Chile SpA y Uber Portier Chile SpA; controlador de datos global: Uber Technologies, Inc. / Uber B.V.",
 "categoria": "delivery",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "Estados Unidos",
 "marco_legal_declarado": "T&C Chile: legislación chilena, tribunales de Santiago. Aviso de privacidad global: RGPD (UE/EEE/Reino Unido/Suiza), LGPD (Brasil), KVKK (Turquía), CCPA (California); no cita Ley 19.628 ni Ley 21.719 de Chile",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; biometricos; financieros; comportamiento_navegacion; datos_dispositivo; contenido_generado",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "no_aplica",
 "exposicion_publica_contenido_por_defecto": "no_aplica",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "tribunales_chile",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://www.uber.com/global/es/privacy/notice/",
 "fecha_version_politica": "Aviso de privacidad: 13 de julio de 2026; Términos de Uso Chile: 12 de agosto de 2026",
 "fecha_consulta": "2026-09-02",
 "notas": "Cubre viajes (Uber) y reparto de comida (Uber Eats) bajo el mismo aviso de privacidad global; los T&C sí tienen versión localizada para Chile con jurisdicción en tribunales de Santiago. Comparte datos con socios de marketing (Meta, TikTok, Google) y procesadores de pago internacionales; certificada bajo el Marco de Privacidad de Datos UE-EE.UU.",
},
{
 "plataforma": "Rappi",
 "empresa_operadora": "Rappi Chile SpA (RUT 76.837.223-3); matriz Rappi S.A.S., de origen colombiano",
 "categoria": "delivery",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "Colombia",
 "marco_legal_declarado": "Ley N°19.628 sobre Protección de la Vida Privada; Ley N°19.496 (protección al consumidor); Art. 28 B (anti-spam); no menciona Ley 21.719 ni la nueva Agencia de Protección de Datos",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; financieros; comportamiento_navegacion; datos_dispositivo; contenido_generado",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "no_aplica",
 "exposicion_publica_contenido_por_defecto": "no_aplica",
 "mecanismo_consentimiento": "opt_in",
 "resolucion_disputas": "tribunales_chile",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://legal.rappi.com/chile/politica-de-privacidad/",
 "fecha_version_politica": "no_especifica (no se encontró fecha de última actualización en el documento)",
 "fecha_consulta": "2026-09-02",
 "notas": "Única de las 4 plataformas de e-commerce/delivery que cita explícitamente el número de ley chilena vigente (Ley 19.628) y el tribunal competente ('Juez de letras en lo civil de Santiago'). Comparte datos con Itaú Corpbanca (RappiPay/RappiBank), Amplitude (analítica) y Jumio (verificación de identidad); ofrece plazo de 2 días hábiles para solicitudes de eliminación de datos.",
},
{
 "plataforma": "Banco Santander Chile",
 "empresa_operadora": "Banco Santander Chile (filial de Banco Santander S.A., España)",
 "categoria": "banca",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "España",
 "marco_legal_declarado": "Ley N°19.628; Ley N°20.009; Capítulo 20-7 normativa CMF; Art. 154 Ley General de Bancos (secreto bancario)",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; biometricos; financieros; comportamiento_navegacion; datos_dispositivo",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "no_aplica",
 "exposicion_publica_contenido_por_defecto": "no_aplica",
 "mecanismo_consentimiento": "opt_in",
 "resolucion_disputas": "tribunales_chile",
 "derecho_eliminacion_portabilidad_datos": "parcial",
 "url_politica_privacidad": "https://banco.santander.cl/personas/politica-de-privacidad-portal-santander",
 "fecha_version_politica": "no_especifica",
 "fecha_consulta": "2026-09-02",
 "notas": "Constituido como banco establecido en Chile pero de control accionario español, por eso se clasifica como transnacional; comparte datos con empresas del grupo Santander a nivel mundial; no se verificó mención explícita a DICOM/Boletín Comercial ni a la Ley 21.719 en el texto consultado.",
},
{
 "plataforma": "Banco de Chile",
 "empresa_operadora": "Banco de Chile (RUT 97.004.000-5)",
 "categoria": "banca",
 "naturaleza_publico_privado": "privada_nacional",
 "pais_origen_matriz": "Chile",
 "marco_legal_declarado": "Ley N°19.628; Arts. 14 y 154 Ley General de Bancos; Art. 155 LGB; Capítulo 20-7 normativa CMF",
 "datos_personales_recolectados": "identificacion; contacto; financieros; comportamiento_navegacion",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "no_especifica",
 "uso_publicitario_perfilamiento": "no_aplica",
 "exposicion_publica_contenido_por_defecto": "no_aplica",
 "mecanismo_consentimiento": "opt_in",
 "resolucion_disputas": "no_especifica",
 "derecho_eliminacion_portabilidad_datos": "parcial",
 "url_politica_privacidad": "https://sitiospublicos.bancochile.cl/personas/politica-de-privacidad",
 "fecha_version_politica": "no_especifica",
 "fecha_consulta": "2026-09-02",
 "notas": "Controlado mayoritariamente por Quiñenco (grupo Luksic, Chile), con participación minoritaria de Citigroup vía LQ Inversiones Financieras. El documento menciona comunicar deudas morosas a 'registros o bancos de datos personales' (referencia funcional a burós tipo Boletín Comercial/DICOM, sin nombrarlos); no se encontró mención de transferencia internacional ni de la Ley 21.719.",
},
{
 "plataforma": "BCI (Banco de Crédito e Inversiones)",
 "empresa_operadora": "Banco de Crédito e Inversiones (BCI)",
 "categoria": "banca",
 "naturaleza_publico_privado": "privada_nacional",
 "pais_origen_matriz": "Chile",
 "marco_legal_declarado": "Ley N°19.628; Capítulo 20-7 normativa CMF; menciona UAF y SII",
 "datos_personales_recolectados": "identificacion; contacto; financieros; biometricos",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "no_aplica",
 "exposicion_publica_contenido_por_defecto": "no_aplica",
 "mecanismo_consentimiento": "opt_in",
 "resolucion_disputas": "no_especifica",
 "derecho_eliminacion_portabilidad_datos": "parcial",
 "url_politica_privacidad": "https://cdn3.bci.cl/uploads/80238e39-0122-4737-a288-7c3468b3c964/original/Terminos_politicas_y_condiciones_b49b786d21_72b5394e31.pdf",
 "fecha_version_politica": "no_especifica",
 "fecha_consulta": "2026-09-02",
 "notas": "Controlado por familia Yarur (Chile); posee filiales en el extranjero (City National Bank of Florida, EE.UU.). Menciona explícitamente comunicar deudas impagas a 'registros o bancos de datos personales' (referencia funcional a burós de crédito tipo DICOM/Boletín Comercial, sin nombrarlos); no menciona la Ley 21.719.",
},
{
 "plataforma": "BancoEstado",
 "empresa_operadora": "Banco del Estado de Chile (BancoEstado)",
 "categoria": "banca",
 "naturaleza_publico_privado": "publica_estatal",
 "pais_origen_matriz": "Chile",
 "marco_legal_declarado": "no_especifica",
 "datos_personales_recolectados": "no_especifica",
 "comparte_datos_terceros": "no_especifica",
 "transferencia_internacional_datos": "no_especifica",
 "uso_publicitario_perfilamiento": "no_especifica",
 "exposicion_publica_contenido_por_defecto": "no_aplica",
 "mecanismo_consentimiento": "no_especifica",
 "resolucion_disputas": "no_especifica",
 "derecho_eliminacion_portabilidad_datos": "no_especifica",
 "url_politica_privacidad": "https://www.bancoestado.cl/content/bancoestado-public/cl/es/home/politica-de-privacidad-y-uso---bancoestado.html",
 "fecha_version_politica": "no_especifica",
 "fecha_consulta": "2026-09-02",
 "notas": "No fue posible verificar el contenido: el dominio bancoestado.cl devolvió error 404 ante todas las solicitudes automatizadas, pese a múltiples intentos. Por ser banco estatal, su tratamiento de datos estaría sujeto además a normativa de administración pública/transparencia, pero esto no se pudo confirmar en la política vigente. Requiere verificación manual directa (navegador) antes de incorporar al análisis final.",
},
{
 "plataforma": "ClaveÚnica / ChileAtiende (gob.cl)",
 "empresa_operadora": "Instituto de Previsión Social (IPS, opera ChileAtiende); ClaveÚnica administrada por la Secretaría de Gobierno Digital (SGD, Min. Hacienda) junto al Servicio de Registro Civil e Identificación",
 "categoria": "gobierno",
 "naturaleza_publico_privado": "publica_estatal",
 "pais_origen_matriz": "Chile",
 "marco_legal_declarado": "Ley 19.628 (art. 20); Art. 19 N°4 Constitución; Ley 20.255 art.56; Ley 18.834 art.61 h); Ley 20.530 art.10; Ley 20.584 art.12; Ley 21.663 (Marco Ciberseguridad); Ley 21.658 (crea la SGD); Ley 21.719 (mencionada como reforma entrante por la política de la SGD)",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; comportamiento_navegacion; datos_dispositivo",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "no_especifica",
 "uso_publicitario_perfilamiento": "no_aplica",
 "exposicion_publica_contenido_por_defecto": "no_aplica",
 "mecanismo_consentimiento": "obligatorio_por_ley",
 "resolucion_disputas": "via_administrativa_estado",
 "derecho_eliminacion_portabilidad_datos": "parcial",
 "url_politica_privacidad": "https://www.chileatiende.gob.cl/politica-de-privacidad",
 "fecha_version_politica": "no_especifica",
 "fecha_consulta": "2026-09-02",
 "notas": "La política de ChileAtiende autoriza expresamente comunicar datos a 'otros organismos del Estado u otros terceros' (interoperabilidad estatal) y no menciona la Ley 21.719; en cambio, la política de tratamiento de datos de la SGD (que administra ClaveÚnica) sí la referencia explícitamente como reforma entrante (vigencia plena 01-12-2026, aún no alcanzada a la fecha de consulta) y declara no realizar perfilamiento ni decisiones automatizadas.",
},
{
 "plataforma": "Servicio de Impuestos Internos (SII)",
 "empresa_operadora": "Servicio de Impuestos Internos",
 "categoria": "gobierno",
 "naturaleza_publico_privado": "publica_estatal",
 "pais_origen_matriz": "Chile",
 "marco_legal_declarado": "Art. 19 N°4 Constitución; Ley 19.628 arts. 4 y 20; DS N°14/2014; DS N°1/2015; Ley Orgánica del SII art. 4° bis; Ley 17.336 (propiedad intelectual); Ley 20.285 (transparencia)",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; comportamiento_navegacion; datos_dispositivo; datos_laborales",
 "comparte_datos_terceros": "parcial",
 "transferencia_internacional_datos": "no_especifica",
 "uso_publicitario_perfilamiento": "no_aplica",
 "exposicion_publica_contenido_por_defecto": "no_aplica",
 "mecanismo_consentimiento": "obligatorio_por_ley",
 "resolucion_disputas": "via_administrativa_estado",
 "derecho_eliminacion_portabilidad_datos": "parcial",
 "url_politica_privacidad": "https://www.sii.cl/sobre_el_sii/declaracion_de_privacidad.html",
 "fecha_version_politica": "no_especifica",
 "fecha_consulta": "2026-09-02",
 "notas": "Ni la declaración de privacidad ni los términos del sitio mencionan la Ley 21.719 ni la nueva Agencia de Protección de Datos. Los derechos de acceso/rectificación/cancelación/oposición (Ley 19.628) se ejercen por 'canales tributarios internos' (art. 16). El documento no itemiza explícitamente datos tributarios/financieros pese a ser el núcleo de la función del SII.",
},
{
 "plataforma": "Fondo Nacional de Salud (Fonasa)",
 "empresa_operadora": "Fondo Nacional de Salud (Fonasa), organismo público dependiente del Ministerio de Salud",
 "categoria": "salud",
 "naturaleza_publico_privado": "publica_estatal",
 "pais_origen_matriz": "Chile",
 "marco_legal_declarado": "Ley 20.285 (transparencia); Ley 19.223 (delitos informáticos); Ley 19.628 (protección vida privada); Ley 19.880 (procedimiento administrativo); Ley 19.927 (delitos pornografía infantil)",
 "datos_personales_recolectados": "no_especifica",
 "comparte_datos_terceros": "parcial",
 "transferencia_internacional_datos": "no_especifica",
 "uso_publicitario_perfilamiento": "no_aplica",
 "exposicion_publica_contenido_por_defecto": "no_aplica",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "no_especifica",
 "derecho_eliminacion_portabilidad_datos": "no_especifica",
 "url_politica_privacidad": "https://www.fonasa.gob.cl/condiciones-de-uso/",
 "fecha_version_politica": "2024-11-14",
 "fecha_consulta": "2026-09-02",
 "notas": "Fonasa no presenta una política de privacidad separada: el tratamiento de datos se describe dentro de 'Condiciones de Uso', que declara no compartir datos con terceros salvo prestadores con relación directa y autorización previa del usuario. No itemiza categorías de datos (p. ej. datos de salud) ni menciona la Ley 21.719; tampoco detalla mecanismo formal de resolución de disputas ni derechos de eliminación/portabilidad.",
},
{
 "plataforma": "Netflix",
 "empresa_operadora": "Netflix, Inc.",
 "categoria": "streaming",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "Estados Unidos",
 "marco_legal_declarado": "CCPA; leyes estatales de privacidad de EE.UU.; referencia genérica al Pacto Internacional de Derechos Civiles y Políticos; no menciona Ley 19.628 ni Ley 21.719",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; financieros; comportamiento_navegacion; contenido_generado; datos_dispositivo; biometricos",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "no_aplica",
 "exposicion_publica_contenido_por_defecto": "no_aplica",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "arbitraje_privado",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://help.netflix.com/legal/privacy",
 "fecha_version_politica": "10 de abril de 2026",
 "fecha_consulta": "2026-09-02",
 "notas": "Términos de Uso (misma fecha de versión) fijan arbitraje vía JAMS bajo ley de Delaware, con posibilidad de litigios coordinados en tribunales de Los Ángeles/California; no se identificó subsidiaria chilena como controlador de datos. Ofrece opt-out específico para publicidad conductual (DAA/EDAA/DAAC).",
},
{
 "plataforma": "Google (Cuenta de Google: Gmail, Search, YouTube, etc.)",
 "empresa_operadora": "Google LLC (matriz: Alphabet Inc.)",
 "categoria": "servicios_generales",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "Estados Unidos",
 "marco_legal_declarado": "Menciona 'marcos legales de transferencia de datos' sin nombrar explícitamente RGPD/CCPA/LGPD en el cuerpo principal consultado; Términos de Servicio regidos por ley de California, EE.UU.; no menciona Ley 19.628 ni Ley 21.719",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; biometricos; financieros; comportamiento_navegacion; contenido_generado; datos_dispositivo; datos_salud",
 "comparte_datos_terceros": "parcial",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "si",
 "exposicion_publica_contenido_por_defecto": "configurable",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "jurisdiccion_extranjera",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://policies.google.com/privacy?hl=es-419",
 "fecha_version_politica": "26 de mayo de 2026 (Política de Privacidad); Términos de Servicio vigentes desde 30 de julio de 2026",
 "fecha_consulta": "2026-09-02",
 "notas": "Disputas resueltas en tribunales estatales/federales de Santa Clara County, California, salvo que la ley local lo impida. Declara no usar contenido de Drive/Gmail/Fotos ni categorías sensibles (salud, orientación, etc.) para publicidad personalizada; menciona 'compliance con reguladores locales' de forma genérica, sin citar la futura Agencia de Protección de Datos chilena.",
},
]

with open("condiciones_de_uso_chile.csv", "w", newline="", encoding="utf-8-sig") as f:
    writer = csv.DictWriter(f, fieldnames=columns, quoting=csv.QUOTE_ALL)
    writer.writeheader()
    for i, row in enumerate(rows, start=1):
        row["id"] = i
        writer.writerow(row)

print(f"Filas escritas: {len(rows)}")
