# -*- coding: utf-8 -*-
NEW_VARS = {
"Facebook e Instagram": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Desde dic-2025 chats con Meta AI alimentan anuncios (sin opt-out); desde jun-2026 los datos de 'actividad en otras empresas' también personalizan el Feed y las respuestas de IA, eliminando el control específico de esa fuente de datos.",
 "version_localizada_chile": "no",
 "gobernanza_moderacion_comportamiento": "explicita_y_detallada",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "si",
 "menciona_bienestar_o_uso_saludable": "si",
 "url_fuente_adicional": "https://about.fb.com/news/2026/06/better-personalization-and-changes-to-controls-for-your-activity-from-other-businesses/",
 "notas_ampliacion": "Mantiene pestañas 'Feeds' (cronológica) vs 'Home' (algorítmica) e Instagram tiene 'Favoritos'/cronológico y 'Recommendations Reset', pero el opt-out de personalización vía datos de terceros para ads/IA fue eliminado en 2026.",
},
"WhatsApp": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "no_aplica",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Meta AI integrado en chats (datos usados para ads en FB/IG desde dic-2025, actualmente excluido en WhatsApp); mayo-2026 lanza 'Incognito Chat' con Meta AI (procesamiento privado, sin guardar conversación); oct-2025 prohíbe chatbots de IA de terceros de propósito general en la API de negocios.",
 "version_localizada_chile": "no",
 "gobernanza_moderacion_comportamiento": "mencionada_sin_detalle",
 "datos_conductuales_para_personalizacion": "no_especifica",
 "regula_trabajo_creadores_o_relacional": "si",
 "menciona_bienestar_o_uso_saludable": "no",
 "url_fuente_adicional": "https://blog.whatsapp.com/introducing-incognito-chat-with-meta-ai-a-completely-private-way-to-chat-with-ai",
 "notas_ampliacion": "No hay feed de contenido personalizado en chats; solo la pestaña 'Actualizaciones/Canales' tiene descubrimiento algorítmico ('Promoted Channels', jun-2025), con monetización incipiente vía Business Solution Terms.",
},
"TikTok": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Etiquetado obligatorio de contenido generado por IA (política de 4 niveles); ofrece herramientas de IA generativa para creadores; no se halló declaración explícita de entrenamiento de modelos con datos de usuarios.",
 "version_localizada_chile": "no",
 "gobernanza_moderacion_comportamiento": "explicita_y_detallada",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "si",
 "menciona_bienestar_o_uso_saludable": "si",
 "url_fuente_adicional": "https://www.tiktok.com/transparency/en/recommendation-system",
 "notas_ampliacion": "La página de soporte declara explícitamente qué señales conductuales alimentan el 'For You' (compras, likes, tiempo visto, búsquedas); existen 'Screen Time'/'Family Pairing'/'Restricted Mode' para todos los usuarios, no solo menores.",
},
"X (antes Twitter)": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Grok (xAI) se entrena con posts públicos e interacciones del usuario en X, con opt-out en Privacidad y seguridad; ToS de ene-2026 amplía 'Contenido' a prompts/inputs/outputs de IA y otorga licencia mundial para entrenar modelos de IA.",
 "version_localizada_chile": "parcial",
 "gobernanza_moderacion_comportamiento": "explicita_y_detallada",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "si",
 "menciona_bienestar_o_uso_saludable": "no",
 "url_fuente_adicional": "https://help.x.com/en/using-x/about-grok",
 "notas_ampliacion": "Existe versión en español (x.com/es/tos) pero la jurisdicción sigue en Tarrant County, Texas, sin entidad chilena; el programa de reparto de ingresos por ads cierra el 7-sep-2026 y es reemplazado por el 'Original Content Rewards Program' (pago por contenido original, no por impresiones).",
},
"LinkedIn": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Desde nov-2025 usa datos de perfil para entrenar IA de Microsoft, con opt-out; el feed usa señales de comportamiento (clics, likes, comentarios, tiempo de visualización) vía un sistema de ranking en dos fases.",
 "version_localizada_chile": "parcial",
 "gobernanza_moderacion_comportamiento": "explicita_y_detallada",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "si",
 "menciona_bienestar_o_uso_saludable": "no",
 "url_fuente_adicional": "https://engineering.linkedin.com/teams/data/artificial-intelligence/feed",
 "notas_ampliacion": "Existe versión en español pero probablemente bajo LinkedIn Ireland, no entidad chilena; Professional Community Policies detalla 5 categorías con moderación en 3 capas; programa de monetización para creadores (BrandLink) es incipiente.",
},
"Mercado Libre / Mercado Pago": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Buscador con IA generativa (Vertex AI de Google) que interpreta la intención del usuario y personaliza resultados según historial de compra; no aparece mencionado en la Declaración de Privacidad vigente.",
 "version_localizada_chile": "si",
 "gobernanza_moderacion_comportamiento": "mencionada_sin_detalle",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "si",
 "menciona_bienestar_o_uso_saludable": "no",
 "url_fuente_adicional": "https://www.mercadopago.cl/privacidad/declaracion-privacidad/current",
 "notas_ampliacion": "'Programa de Afiliados y Creadores' activo en Chile permite monetizar recomendaciones de productos vía comisión — nueva capa 'creator economy' sobre el marketplace; no hay opt-out claro del motor de recomendación en sí.",
},
"Falabella.com (Falabella Retail)": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Proveedor externo (Adereso) con 'suite de IA Generativa' automatiza atención al cliente (caso de terceros, no confirmado en T&C propios); campaña educativa promueve herramientas de IA de terceros, no declara IA propia.",
 "version_localizada_chile": "si",
 "gobernanza_moderacion_comportamiento": "explicita_y_detallada",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "si",
 "menciona_bienestar_o_uso_saludable": "no",
 "url_fuente_adicional": "https://sellercenter.falabella.com/templates/default/files/terminos_y_condiciones_marketplace_falabella.pdf",
 "notas_ampliacion": "T&C de Marketplace detallan prohibiciones específicas para vendedores (falsear reseñas) con sanciones hasta eliminación. Programa 'Creators F' (2025) para creadores de contenido que monetizan recomendaciones — sin T&C públicos detallados verificables.",
},
"Uber / Uber Eats": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "si",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "El Aviso de privacidad de conductores y repartidores declara explícitamente: 'Uber may use GenAI tools for customer support'.",
 "version_localizada_chile": "si",
 "gobernanza_moderacion_comportamiento": "explicita_y_detallada",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "si",
 "menciona_bienestar_o_uso_saludable": "si",
 "url_fuente_adicional": "https://www.uber.com/global/en/privacy-notice-drivers-delivery-people/",
 "notas_ampliacion": "Guías Comunitarias (versión Chile) detallan tres pilares de conducta y derecho a apelar desactivación; el Aviso de privacidad describe uso de patrones de conducción 'atípicos' para acciones automatizadas, incluida desactivación de cuenta.",
},
"Rappi": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Asistente conversacional de IA vía WhatsApp para pedidos; IA que aprende 'de los gustos y hábitos de los usuarios' para ofertas personalizadas; 'Recomendaciones de Menú con IA' para restaurantes (B2B). No confirmado en Política de Privacidad ni T&C de Chile.",
 "version_localizada_chile": "si",
 "gobernanza_moderacion_comportamiento": "mencionada_sin_detalle",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "si",
 "menciona_bienestar_o_uso_saludable": "no",
 "url_fuente_adicional": "https://legal.rappi.com.co/chile/politica-de-privacidad/",
 "notas_ampliacion": "Permite excluirse de listas promocionales ('No Molestar', Ley 19.496), pero no hay opt-out explícito del motor de recomendación. Sistema de calificación 1-5 para repartidores; no se pudo verificar el T&C específico 'Soy Rappi' para Chile.",
},
"Banco Santander Chile": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Grupo Santander anunció alianza con OpenAI (ago-2025, nivel global); en Chile opera desde 2021 el asistente conversacional 'Santi' (WhatsApp/web), sin confirmación pública de IA generativa específica en la operación chilena.",
 "version_localizada_chile": "si",
 "gobernanza_moderacion_comportamiento": "no_menciona",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "no_aplica",
 "menciona_bienestar_o_uso_saludable": "si",
 "url_fuente_adicional": "https://saladecomunicacion.santander.cl/opinion/carmen-gloria-silva/detalles/finanzas-saludables-el-viaje-hacia-el-bienestar-comienza-en-la-infancia",
 "notas_ampliacion": "Política de privacidad cita elaboración de 'perfil de usuario aplicando o no modelos predictivos'; el opt-out solo cubre comunicaciones comerciales, no el perfilamiento general. 'Santi' es marca de chatbot compartida por el Grupo Santander en varios países.",
},
"Banco de Chile": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Chatbot 'FANi' (Dialogflow CX de Google + IA generativa) para apertura de Cuenta FAN; alianza estratégica con Microsoft (oct-2025) que incorpora IA generativa para atención al cliente, análisis predictivo y Copilot Chat para ~12.000 empleados.",
 "version_localizada_chile": "si",
 "gobernanza_moderacion_comportamiento": "mencionada_sin_detalle",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "no_aplica",
 "menciona_bienestar_o_uso_saludable": "si",
 "url_fuente_adicional": "https://news.microsoft.com/source/latam/noticias-de-microsoft/banco-de-chile-es-la-primera-empresa-privada-del-pais-en-sellar-alianza-estrategica-en-ia-con-microsoft/",
 "notas_ampliacion": "Primera empresa privada de Chile con alianza estratégica de IA con Microsoft; política de privacidad menciona 'soluciones personalizadas' y análisis del comportamiento financiero. Programa de educación financiera 'Cuentas con el Chile'.",
},
"BCI (Banco de Crédito e Inversiones)": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Centro de Excelencia en IA Generativa (desde 2024): asistentes con 'humano en el loop' en áreas legal, gestión de activos y atención al cliente; pilotaje de agentes de IA autónomos para 2025. 'Recomendador de Tarjetas' público basado en hábitos de consumo.",
 "version_localizada_chile": "si",
 "gobernanza_moderacion_comportamiento": "no_menciona",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "no_aplica",
 "menciona_bienestar_o_uso_saludable": "si",
 "url_fuente_adicional": "https://www.df.cl/df-lab/tecnologia/centro-de-inteligencia-artificial-de-bci-busca-implementar-los-primeros",
 "notas_ampliacion": "El banco con evidencia más explícita de IA generativa declarada públicamente entre los cuatro. Programas 'Con Letra Grande', 'Mis Finanzas' y 'Alcancía' para educación financiera y prevención de sobreendeudamiento.",
},
"BancoEstado": {
 "usa_recomendacion_algoritmica_declarada": "no_especifica",
 "posibilidad_opt_out_personalizacion": "no_especifica",
 "menciona_ia_generativa": "no",
 "uso_declarado_ia_generativa": "No se encontró declaración pública de IA generativa. Opera un 'asistente virtual' en WhatsApp desde ~2021 para consultas de cuenta, aparentemente basado en menús/reglas, no confirmado como IA generativa.",
 "version_localizada_chile": "si",
 "gobernanza_moderacion_comportamiento": "no_especifica",
 "datos_conductuales_para_personalizacion": "no_especifica",
 "regula_trabajo_creadores_o_relacional": "no_aplica",
 "menciona_bienestar_o_uso_saludable": "si",
 "url_fuente_adicional": "https://www.educacionfinanciera.cl/quienes-somos",
 "notas_ampliacion": "El dominio bancoestado.cl volvió a devolver error 404 en todos los accesos automatizados en un segundo intento de investigación independiente. Programa robusto de educación financiera verificado en subdominio separado. La marca 'si' en version_localizada_chile se infiere estructuralmente (banco 100% estatal), no de un documento verificado.",
},
"ClaveÚnica / ChileAtiende (gob.cl)": {
 "usa_recomendacion_algoritmica_declarada": "no",
 "posibilidad_opt_out_personalizacion": "no_aplica",
 "menciona_ia_generativa": "no_especifica",
 "uso_declarado_ia_generativa": "ChileAtiende ofrece 'Sucursal Virtual' (videollamada humana, explícitamente descrita como 'mejor que un chatbot'); no se halló chatbot/IA generativa propio verificable.",
 "version_localizada_chile": "si",
 "gobernanza_moderacion_comportamiento": "explicita_y_detallada",
 "datos_conductuales_para_personalizacion": "no_especifica",
 "regula_trabajo_creadores_o_relacional": "no_aplica",
 "menciona_bienestar_o_uso_saludable": "no",
 "url_fuente_adicional": "https://claveunica.gob.cl/terminos-y-condiciones",
 "notas_ampliacion": "No se pudo acceder al texto de T&C ni Política de Privacidad de ChileAtiende (error 403); análisis se apoya en su home y fuentes secundarias. Los T&C de ClaveÚnica no mencionan personalización, recomendación ni IA; se centran en seguridad de credenciales.",
},
"Servicio de Impuestos Internos (SII)": {
 "usa_recomendacion_algoritmica_declarada": "no",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Chatbot 'Sofía' (2021, híbrido no generativo); función de 'Resumen elaborado por IA' en el buscador de sii.cl con descargo de no reemplazar la fuente oficial; uso de IA/algoritmos en fiscalización (Operación Renta 2026) para detección de riesgo.",
 "version_localizada_chile": "si",
 "gobernanza_moderacion_comportamiento": "explicita_y_detallada",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "no_aplica",
 "menciona_bienestar_o_uso_saludable": "no",
 "url_fuente_adicional": "https://www.sii.cl/ayudas/asistencia/contactenos.html",
 "notas_ampliacion": "El caso más rico en IA de las tres plataformas estatales: chatbot histórico, resumen automático con IA en buscador, y fiscalización predictiva de riesgo — pero sin evidencia de recomendación de contenido/personalización de experiencia al estilo plataformas sociales.",
},
"Fondo Nacional de Salud (Fonasa)": {
 "usa_recomendacion_algoritmica_declarada": "no",
 "posibilidad_opt_out_personalizacion": "no_aplica",
 "menciona_ia_generativa": "no",
 "uso_declarado_ia_generativa": "no_aplica",
 "version_localizada_chile": "si",
 "gobernanza_moderacion_comportamiento": "mencionada_sin_detalle",
 "datos_conductuales_para_personalizacion": "no_especifica",
 "regula_trabajo_creadores_o_relacional": "no_aplica",
 "menciona_bienestar_o_uso_saludable": "no",
 "url_fuente_adicional": "https://www.fonasa.gob.cl/condiciones-de-uso/",
 "notas_ampliacion": "Las Condiciones de Uso de Fonasa son las más escuetas de las tres estatales: no abordan personalización, datos conductuales, IA ni bienestar; solo referencian marco legal general y sanciones penales.",
},
"Netflix": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "IA generativa documentada en producción de contenido (~300 títulos en 2026, VFX/doblaje), dirigida a estudios/proveedores; el Privacy Statement/ToS dirigido al usuario final NO menciona IA generativa en el tratamiento de datos personales.",
 "version_localizada_chile": "no_especifica",
 "gobernanza_moderacion_comportamiento": "no_menciona",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "no",
 "menciona_bienestar_o_uso_saludable": "no",
 "url_fuente_adicional": "https://help.netflix.com/en/node/100637",
 "notas_ampliacion": "Distinguir 'IA generativa en producción' (B2B, pública) de 'IA generativa en tratamiento de datos del usuario' (no declarada) — son documentos distintos. Toggle de 'Behavioral Advertising' existe, pero no hay opción de apagar el motor de recomendación de contenido.",
},
"Google (Cuenta de Google: Gmail, Search, YouTube, etc.)": {
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Gemini (asistente conversacional) tiene aviso de privacidad separado (Gemini Apps Privacy Hub); la Política de Privacidad general no detalla exhaustivamente el uso de datos de usuario para entrenar modelos.",
 "version_localizada_chile": "parcial",
 "gobernanza_moderacion_comportamiento": "mencionada_sin_detalle",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "no_aplica",
 "menciona_bienestar_o_uso_saludable": "si",
 "url_fuente_adicional": "https://support.google.com/gemini/answer/13594961",
 "notas_ampliacion": "Confirma dato ya conocido: 'We don't show you personalized ads based on your content from Drive, Gmail, or Photos'. Google promueve herramientas de 'Digital Wellbeing' (Android) como característica declarada del ecosistema.",
},
}

NEW_ROWS = [
{
 "plataforma": "YouTube",
 "empresa_operadora": "YouTube, LLC (subsidiaria de Google LLC / Alphabet Inc.)",
 "categoria": "streaming",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "Estados Unidos",
 "marco_legal_declarado": "ToS propio cita 'California law' (excluyendo reglas de conflicto de leyes); no cita GDPR/CCPA por nombre en el ToS mismo. El tratamiento de datos se rige por la Política de Privacidad de Google, que sí referencia marcos regionales vía anexos/centros de ayuda regionales.",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; comportamiento_navegacion; contenido_generado; datos_dispositivo; financieros",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "si",
 "exposicion_publica_contenido_por_defecto": "configurable",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "jurisdiccion_extranjera",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://www.youtube.com/t/terms",
 "fecha_version_politica": "ToS de YouTube: 15 de diciembre de 2023; Política de Privacidad de Google: efectiva 26 de mayo de 2026",
 "fecha_consulta": "2026-09-02",
 "notas": "Perfil nuevo agregado en la ampliación del corpus (eje 'algorithmic sociality'). YouTube no tiene política de privacidad propia; hereda la de Google (cuenta unificada).",
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "Etiquetado obligatorio de contenido alterado/sintético realista (deepfakes, voces sintéticas); política de contenido 'inauténtico'/masivo generado por IA que puede restringir monetización en el Programa de Socios (YPP).",
 "version_localizada_chile": "parcial",
 "gobernanza_moderacion_comportamiento": "explicita_y_detallada",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "si",
 "menciona_bienestar_o_uso_saludable": "si",
 "url_fuente_adicional": "https://support.google.com/youtube/answer/9288567",
 "notas_ampliacion": "El sistema de recomendación se declara en documentación separada ('How YouTube Works'), NO en el ToS mismo, que es notablemente escueto al respecto — un patrón de desplazamiento de la transparencia hacia documentos no contractuales que se repite en varias plataformas del corpus.",
},
{
 "plataforma": "Spotify",
 "empresa_operadora": "Spotify AB (Suecia); Spotify USA Inc. en EE.UU.; matriz bursátil Spotify Technology S.A. (Luxemburgo)",
 "categoria": "streaming",
 "naturaleza_publico_privado": "privada_transnacional",
 "pais_origen_matriz": "Suecia",
 "marco_legal_declarado": "Versión Chile/internacional: ley sueca aplica, con arbitraje ICC; referencias explícitas a GDPR (Art. 15). Versión EE.UU.: ley de Nueva York + arbitraje NAM.",
 "datos_personales_recolectados": "identificacion; contacto; ubicacion; financieros; comportamiento_navegacion; contenido_generado; datos_dispositivo",
 "comparte_datos_terceros": "si",
 "transferencia_internacional_datos": "si",
 "uso_publicitario_perfilamiento": "si",
 "exposicion_publica_contenido_por_defecto": "configurable",
 "mecanismo_consentimiento": "aceptacion_tacita",
 "resolucion_disputas": "arbitraje_privado",
 "derecho_eliminacion_portabilidad_datos": "si_explicito",
 "url_politica_privacidad": "https://www.spotify.com/cl/legal/end-user-agreement/",
 "fecha_version_politica": "Acuerdo de usuario final (versión Chile): 26 de agosto de 2025; Política de Privacidad (versión US consultada): efectiva 1 de julio de 2026",
 "fecha_consulta": "2026-09-02",
 "notas": "Perfil nuevo agregado en la ampliación del corpus. Playlists nuevas y perfil/actividad ('Friend Activity') son públicos por defecto salvo que el usuario los cambie.",
 "usa_recomendacion_algoritmica_declarada": "si",
 "posibilidad_opt_out_personalizacion": "parcial",
 "menciona_ia_generativa": "si",
 "uso_declarado_ia_generativa": "AI DJ: locutor con voz generada por IA que selecciona y presenta música personalizada; AI Playlist: generación de listas de reproducción a partir de prompts de texto.",
 "version_localizada_chile": "parcial",
 "gobernanza_moderacion_comportamiento": "explicita_y_detallada",
 "datos_conductuales_para_personalizacion": "si",
 "regula_trabajo_creadores_o_relacional": "si",
 "menciona_bienestar_o_uso_saludable": "no",
 "url_fuente_adicional": "https://www.spotify.com/platform-rules/",
 "notas_ampliacion": "Existe URL localizada (/cl/legal/end-user-agreement/) en español, pero el contenido legal (ley sueca, arbitraje ICC) es idéntico al default internacional, sin cláusulas propias de Chile — mismo patrón de 'localización cosmética' observado en Google/YouTube.",
},
]
